### ISSUE TITLE
Telegram -> IRC messages not sent

### ISSUE THREAD

**Issue by danielsarin** [FruitieX/teleirc#14]
Hi,

I can't get messages from Telegram to IRC working. Messages from IRC to Telegram work fine.

At startup I get the following errors when running in debug mode

```
Unhandled message: { prefix: 'irc.nebula.fi',
  server: 'irc.nebula.fi',
  command: '020',
  rawCommand: '020',
  commandType: 'normal',
  args: [ '*', 'Please wait while we process your connection.' ] }
```
```
Unhandled message: { prefix: 'irc.nebula.fi',
  server: 'irc.nebula.fi',
  command: '042',
  rawCommand: '042',
  commandType: 'normal',
  args: [ 'tgBot', '<id>', 'your unique ID' ] }
```

After that I don't get any errors. Telegram messages simply disappear somewhere and never show up in IRC. The tgBot does connect to the IRC channel fine.

Any ideas? I have set the config.js and chat_ids, they should be fine.

Could it maybe be a privilege issue? I installed node and npm as a non-sudo user and I'm running teleirc as non-sudo as well. Can this have an effect? Anyway to check or fix it?

**Comment by ostPavel** [comment]
I have the opposite, Telegram->IRC works, but not vice versa :\

**Comment by ostPavel** [comment]
@danielsarin Have you given access the messages to the TG bot? It's done in Telegram by sending /setprivacy command to @BotFather.

**Comment by danielsarin** [comment]
Yes I have done that. I have irc_channel_id empty as well.

**Comment by FruitieX** [comment]
Hello, sorry for the late reply and lack of documentation. The handling of this is a little bit odd at the moment, I'm not *really* happy with how a pull request I accepted is doing this. I will be improving the situation right away.

You do indeed need `irc_channel_id` set at the moment to the exact channel name. `irc_channel` is just an alias of the channel which will be displayed in the IRC -> Telegram message. The reason for this was to show IRCnet's !-channels a little nicer in Telegram. I will rewrite this so that the config file contains clearer options, and so that the current `irc_channel` and `irc_channel_id` don't both have to be specified.

**Comment by FruitieX** [comment]
Okay, this confusion should now be avoided in the [refactor](https://github.com/FruitieX/teleirc/tree/refactor) branch. Check out the new [example config](https://github.com/FruitieX/teleirc/blob/refactor/config.js.example). You can either try the branch out right now, or wait for the 0.3.0 npm module release.

I'll close this issue once I'm confident enough with the changes to release a new version.
